### ISSUE TITLE
Consider adding async-graphql-relay to SeaORM showcase!

### ISSUE THREAD

**Issue by billy1624** [oscartbeaumont/async-graphql-relay#12]
Hey @oscartbeaumont, feel free to submit a PR to showcase your project!
- https://github.com/SeaQL/sea-orm/issues/403

**Comment by oscartbeaumont** [comment]
I am closing this as I have stopped using this project and do not intend to continue maintaining it to the level required to be promoting it.

Thanks for your consideration of adding it to the showcase!
