### ISSUE TITLE
What is blocking a new release?

### ISSUE THREAD

**Issue by aidangilmore** [oscartbeaumont/async-graphql-relay#24]
In [this commit](https://github.com/oscartbeaumont/async-graphql-relay/commit/04dc850ce1e8bf6862656084828ef7e2f8e2c293) you mention something about waiting on an upstream issue with `async-graphql`. Does that remain an issue?

**Comment by oscartbeaumont** [comment]
I can't fully remember but looking at the dates it would be [this](https://github.com/async-graphql/async-graphql/issues/763) which looks to have been fixed. I should have linked to the issue I referred to in the commit :facepalm:.

I will look into doing a new release of this library as soon as I can find some time.

**Comment by aidangilmore** [comment]
Thanks, let me know if you need a hand.

**Comment by oscartbeaumont** [comment]
Imma just keep this issue open until I finish it as a reminder.

**Comment by satvikpendem** [comment]
Any updates on this? I was thinking of using async-graphql-relay since my frontend is in Relay. The current version works I'm guessing? Maybe the dependabot PRs could be merged as well.

**Comment by oscartbeaumont** [comment]
I have just done a quick dependency update and publish.

I am not actively using this project any more so I can't commit to continue maintaining it but would be happy to merge and publish PR's if changes are needed.

I would be happy to hand over to another maintainer but they would need to prove themselves before I am willing to do that.

**Comment by satvikpendem** [comment]
Thanks, does it still work fine or are there any breaking or showstopping issues?
